[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "VOICE_app"
version = "0.1.0"
description = "VOICE_app napari plugin for synthetic organelle LR/SR dataset generation."
readme = "README.md"
requires-python = ">=3.10,<3.11"
license = "LicenseRef-Proprietary"
authors = [
  { name = "VOICE_app" }
]
classifiers = [
  "Framework :: napari",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
]
dependencies = [
  "magicgui",
  "napari",
  "numpy",
  "qtpy",
  "scipy",
  "tifffile",
]

[project.entry-points."napari.manifest"]
VOICE_app = "voice_app:napari.yaml"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
voice_app = ["napari.yaml", "*.pyc"]

[tool.setuptools.exclude-package-data]
voice_app = ["._*", "__pycache__/*"]
